### ISSUE TITLE
Diseño en figma|zeplin para maquetar? 

### ISSUE THREAD

**Issue by romelgomez** [ngVenezuela/ngvenezuela-org#4]
Seria super que hubiera una diseño de lo que se quiere lograr para maquetar el proyecto.

**Comment by Villanuevand** [comment]
Hola @romelgomez , 

Gracias por mostrar interés en el proyecto. Es un proyecto que está en fase inicial, no tenemos por ahora un diseño pautado. Tenemos una idea de lo que vamos a hacer que vamos a intentar descargar en un issue de github y de ahi trabajar bajo lineamientos comunes más no muy específicos, por lo que la creatividad es bienvenida. 

Atento, a los issues, 

Saludos
